#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinAndroidPoiApp.Resource", IsApplication=true)]

namespace XamarinAndroidPoiApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060017
			public const int actionDelete = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int actionNew = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int actionRefresh = 2131099673;
			
			// aapt resource value: 0x7f060016
			public const int actionSave = 2131099670;
			
			// aapt resource value: 0x7f060007
			public const int addrEditText = 2131099655;
			
			// aapt resource value: 0x7f060014
			public const int addrTextView = 2131099668;
			
			// aapt resource value: 0x7f060005
			public const int descrEditText = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int latEditText = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int longEditText = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int nameEditText = 2131099651;
			
			// aapt resource value: 0x7f060013
			public const int nameTextView = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int poiImageView = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int poiListView = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int progressBar = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int relativeLayout1 = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int scrollView1 = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int tableLayout1 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int tableRow2 = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow3 = 2131099660;
			
			// aapt resource value: 0x7f060015
			public const int textView1 = 2131099669;
			
			// aapt resource value: 0x7f060002
			public const int textView10 = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int textView11 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int textView12 = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int textView21 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int textView22 = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int POIDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int POIList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int POIListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int POIDetailMenu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int POIListViewMenu = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int address_hint = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int distance_hint = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int poi_name_hint = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
